### ISSUE TITLE
Crashing in the nether

### ISSUE THREAD

**Issue by gmatik** [kyber-6/symbolica-modpack#3]
### Describe the bug

As soon as i enter the nether and the chunk im in starts loading, game freezes and crashes

### Reproduction steps

Enter nether i guess?

### Logs & crash-reports

[crash-2023-12-17_15.09.31-client.txt](https://github.com/kyber-6/symbolica-modpack/files/13696054/crash-2023-12-17_15.09.31-client.txt)

### Mod pack version

Symbolica 1.2.5

**Comment by kyber-6** [comment]
Try disabling the Doctor Who - Weeping Angels mod.

**Comment by gmatik** [comment]
that solved it, thanks!
